### ISSUE TITLE
How i can fix this error:  ECONNREFUSED   ?

### ISSUE THREAD

**Issue by CarlitoXD** [cnect/sails-sqlserver-adapter#2]
{ [ConnectionError: Failed to connect to 10.65.11.135:1433 - connect ECONNREFUSED]
  name: 'ConnectionError',
  message: 'Failed to connect to 10.65.11.135:1433 - connect ECONNREFUSED',
  code: 'ESOCKET' }

**Comment by tjwebb** [comment]
Can you connect to the same host using SQL Server Management Studio or other similar mssql client? `ECONNREFUSED` would usually indicate that whatever host you're contacting simply is not listening on port `1433` at all.

**Comment by CarlitoXD** [comment]
Yes, i can connect with other client, i am using DBeaver Client.
But, i need to pass the instance and domain for example:

instance: 'SQLEXPRESS',
domain: 'domain.local'

**Comment by tjwebb** [comment]
What is `instance`? This is not a property that is supported by this adapter.

Please make sure you are using `sails-sqlserver-adapter`, and not one of the other two similarly named adapters, "sails-mssql" or "sails-sqlserver".

**Comment by CarlitoXD** [comment]
the "instance name" and domain is required in SQL Server 2012 for the authentication.
I will  test without this params.

thanks for your help.

**Comment by tjwebb** [comment]
"instance" and "domain" are not properties currently supported by this
adapter. I've tested this on SQL server 2012 and 2014 and have not seen
these fields required.

If you'd like to add them, PR s are welcome.
